### ISSUE TITLE
Help With Import_Gamrecord.

### ISSUE THREAD

**Issue by Joness07** [ripieces/afx-sfm-scripts#1]
I have the latest version of the SFM scripts and when I try importing my .agr file it says "Version 4 is not supported". I've tried other versions of the scripts and it seems to result in the same outcome. Its probably something that I am doing wrong so is there anything I could try to make this work?

Thanks In advance

**Comment by dtugend** [comment]
This one can import version 4:
https://github.com/advancedfx/afx-sfm-scripts/releases/tag/v1.6.0

Make sure to update your HLAE, because version 5 is the latest one atm.

**Comment by dtugend** [comment]
Version 4: https://github.com/advancedfx/afx-sfm-scripts/releases/tag/v1.6.0
Version 5: https://github.com/advancedfx/afx-sfm-scripts/releases/tag/v1.7.0
