### ISSUE TITLE
Version out of date

### ISSUE THREAD

**Issue by qu2izno** [ripieces/afx-sfm-scripts#2]
Version 6 is not supported, atleast for gameRecord.py, have not tested with other files.
![version](https://user-images.githubusercontent.com/90019975/176714730-fb63ada6-9d38-4017-8fbc-f32a6d03137c.png)

**Comment by dtugend** [comment]
Thank you for reporting the issue.
I tried to fix it here: https://github.com/advancedfx/afx-sfm-scripts/releases/tag/v1.7.2
